name: Update submodules

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: residwi/dotfiles
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive --remote

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Update submodules to latest commit" || echo "No changes to commit"
          git push
